config/routes.rb
Rails.application.routes.draw do
  resources :events
  root 'events#index'
  get '/new_ticket', to: 'events#new_ticket'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
	has_many :tickets ,dependent: :destroy
	accepts_nested_attributes_for :tickets
end

app/models/ticket.rb
class Ticket < ApplicationRecord
	belongs_to :tickets
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
before_action :set_event ,only:[:edit,:show,:update]
  def index
      @events = Event.all
  end
  def new_ticket
    @ticket = Ticket.new
  end
  def show

  end
  def create
    byebug
  end

  def new
  	@event = Event.new
  	@ticket = Ticket.new
  end

  def edit
  	
  end
  def destroy
  	
  end


  private

  def set_event
  	# @event = Event.find(params[:id])
  end

  def set_params
  	# params.require(:event)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# def link_to_add_ticket(obj , assosiation)
	# 	new_ticket = obj.object.send(assosiation)
	# end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_event.html.erb
<div class="event-booking">	
	<%=form_for @event do |f|%>
	  <div class="row">
		<%= f.label :name%>
		<%= f.text_field :name%>
		<%= f.label :place%>
		<%= f.text_field :place%>
	  </div>
	<div class="row">
     <%=link_to  new_ticket_path ,class:'btn btn-primary',:id=>'add_tickets',method: :get,:remote=> true do%>
     Add tickets
     <%end%>
<!-- 	  <%#= form_tag events_new_ticket_path ,remote: true do%>
		<%#= submit_tag 'Add tickets', class:'btn btn-primary'%>
	  <%#end%> -->
	</div>
	<div class="row" style="margin:0px;"">
	    <div class="ticket-booking">
	    </div>	
	</div>
	<%=f.submit :submit%>	
	<%end%>
</div>

<script>
$(function() {
	$('.datetimepicker').datetimepicker();
	// body... 
})
</script>

app/views/events/_ticket.html.erb
<%= form_for(@ticket,:url=>events_path) do |ff|%>
	<%=ff.text_field :time,:class=>'datetimepicker'%>
	<%= ff.text_field :audience%>
<%end%>

app/views/events/index.html.erb
<div class="container">
	<h1>Event Manament..!!</h1>
<!-- List of Events -->
</div>

app/views/events/new.html.erb
<h2> Create a Event</h2> 
<div class="container">
	<%= render 'event', locals:{:event=>@event}%>
</div>

<script type="text/javascript">
	$('.datetimepicker').datetimepicker();
</script>

app/views/events/new_ticket.js.erb
 $('.ticket-booking').append('<%= escape_javascript(render 'ticket',:ticket=>@ticket)%>');

app/views/events/show.html.erb
<h1>Events#show</h1>
<p>Find me in app/views/events/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestEvent</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>